spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_study?characterEncoding=utf-8&SSL=false
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  jpa:
    show-sql: true
